lastupdatecheck: 0
recentrepos:
- /home/daimyo/Dev/ict203-Assignment1
- /home/daimyo/Dev/nn
- /home/daimyo/Theme/shell
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
